# Generated by Django 5.0.9 on 2026-04-19 16:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("town", "Town"),
                            ("municipality", "Municipality"),
                            ("district", "District / Neighborhood"),
                            ("county", "County / Region"),
                            ("state", "State / Federal State"),
                            ("other", "Other"),
                        ],
                        default="city",
                        max_length=20,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 (e.g. DE, AT, FR, NL)",
                        max_length=2,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Federal state, province, département, canton, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        default="de",
                        help_text="Default UI language for this workspace",
                        max_length=10,
                    ),
                ),
                ("timezone", models.CharField(default="Europe/Berlin", max_length=50)),
                ("population", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "area_km2",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("description_de", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                (
                    "is_demo",
                    models.BooleanField(
                        default=False,
                        help_text="Showcase workspace — not a production deployment",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bounds",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Rough bounding box for map centering and Overpass queries",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "center",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True,
                        help_text="Default map center for this workspace",
                        null=True,
                        srid=4326,
                    ),
                ),
                ("default_zoom", models.PositiveSmallIntegerField(default=12)),
                (
                    "scoring_weights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Dimension → weight mapping. Defaults used if empty.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_demo", "name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "slug")},
            },
        ),
    ]
