# Generated by Django 5.0.9 on 2026-08-18 19:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0003_workspace_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100)),
                ("name", models.CharField(max_length=200)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("drawn", "Drawn on the map"),
                            ("adopted", "Adopted from an existing area"),
                            ("bbox", "Map viewport"),
                        ],
                        default="drawn",
                        max_length=20,
                    ),
                ),
                (
                    "origin_ref",
                    models.CharField(
                        blank=True,
                        help_text="Where an adopted geometry came from (layer and feature name).",
                        max_length=300,
                    ),
                ),
                ("description_de", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="focus_areas",
                        to="workspaces.district",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="focus_areas",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("workspace", "slug")},
            },
        ),
    ]
