"""
Measure model — a prioritized mobility intervention proposal.

Measures are either auto-generated by the rule engine or hand-curated.
Every measure carries a breakdown of transparent scores and links to its
evidence, per the transparency principle in CLAUDE.md.
"""

from django.contrib.gis.db import models as gis_models
from django.db import models
from django.utils.translation import gettext_lazy as _


class Measure(models.Model):
    class Category(models.TextChoices):
        BIKE_INFRA = "bike_infra", _("Bike infrastructure")
        PEDESTRIAN = "pedestrian", _("Pedestrian / walkability")
        TRANSIT = "transit", _("Public transit")
        PARKING = "parking", _("Parking management")
        SPEED = "speed", _("Speed / traffic calming")
        ACCESS = "access", _("Accessibility / barrier-free")
        SCHOOL_ROUTES = "school_routes", _("School routes")
        MOBILITY_HUB = "mobility_hub", _("Mobility hub")
        PUBLIC_SPACE = "public_space", _("Public space reclamation")
        OTHER = "other", _("Other")

    class EffortLevel(models.TextChoices):
        QUICK_WIN = "quick_win", _("Quick win")
        MEDIUM = "medium", _("Medium effort")
        MAJOR = "major", _("Major project")

    class Status(models.TextChoices):
        PROPOSED = "proposed", _("Proposed")
        PLANNED = "planned", _("Planned")
        IN_PROGRESS = "in_progress", _("In progress")
        DONE = "done", _("Done")
        REJECTED = "rejected", _("Rejected")

    workspace = models.ForeignKey(
        "workspaces.Workspace", on_delete=models.CASCADE, related_name="measures"
    )
    slug = models.SlugField(max_length=120)
    category = models.CharField(max_length=30, choices=Category.choices, default=Category.OTHER)

    title_de = models.CharField(max_length=300)
    title_en = models.CharField(max_length=300, blank=True)
    summary_de = models.CharField(max_length=500, blank=True)
    summary_en = models.CharField(max_length=500, blank=True)
    description_de_md = models.TextField(blank=True)
    description_en_md = models.TextField(blank=True)

    geometry = gis_models.GeometryField(null=True, blank=True, srid=4326)
    district = models.ForeignKey(
        "workspaces.District",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="measures",
    )

    status = models.CharField(
        max_length=20, choices=Status.choices, default=Status.PROPOSED
    )
    effort_level = models.CharField(
        max_length=20, choices=EffortLevel.choices, default=EffortLevel.MEDIUM
    )

    is_auto_generated = models.BooleanField(default=False)
    evidence = models.JSONField(
        default=dict,
        blank=True,
        help_text=_("Raw indicators and debug info supporting this measure."),
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = [("workspace", "slug")]
        ordering = ["workspace", "-updated_at"]

    def __str__(self):
        return f"{self.workspace.slug}/{self.slug}"

    def title_localized(self, language_code: str) -> str:
        if language_code.startswith("en") and self.title_en:
            return self.title_en
        return self.title_de

    def summary_localized(self, language_code: str) -> str:
        if language_code.startswith("en") and self.summary_en:
            return self.summary_en
        return self.summary_de

    def description_localized(self, language_code: str) -> str:
        if language_code.startswith("en") and self.description_en_md:
            return self.description_en_md
        return self.description_de_md


class MeasureScore(models.Model):
    class Dimension(models.TextChoices):
        CLIMATE = "climate", _("Climate impact")
        SAFETY = "safety", _("Traffic safety")
        QUALITY_OF_LIFE = "quality_of_life", _("Quality of life")
        SOCIAL = "social", _("Social equity / accessibility")
        FEASIBILITY = "feasibility", _("Feasibility")
        COST = "cost", _("Cost indicator")
        VISIBILITY = "visibility", _("Public visibility")
        POLITICAL = "political", _("Political viability")
        GOAL_ALIGNMENT = "goal_alignment", _("Alignment with local goals")

    class Confidence(models.TextChoices):
        LOW = "low", _("Low")
        MEDIUM = "medium", _("Medium")
        HIGH = "high", _("High")

    measure = models.ForeignKey(Measure, on_delete=models.CASCADE, related_name="scores")
    dimension = models.CharField(max_length=30, choices=Dimension.choices)

    raw_value = models.FloatField(help_text=_("Normalized 0.0–1.0"))
    display_value = models.FloatField(help_text=_("Display-friendly 0–100"))
    confidence = models.CharField(
        max_length=10, choices=Confidence.choices, default=Confidence.MEDIUM
    )

    rationale_de = models.TextField(blank=True)
    rationale_en = models.TextField(blank=True)

    sources = models.JSONField(default=list, blank=True)

    class Meta:
        unique_together = [("measure", "dimension")]
        ordering = ["dimension"]

    def __str__(self):
        return f"{self.measure.slug}/{self.dimension}"

    def rationale_for(self, language_code: str) -> str:
        if language_code.startswith("en") and self.rationale_en:
            return self.rationale_en
        return self.rationale_de
