# Generated by Django 5.0.9 on 2026-04-19 16:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bike_infra", "Bike infrastructure"),
                            ("pedestrian", "Pedestrian / walkability"),
                            ("transit", "Public transit"),
                            ("parking", "Parking management"),
                            ("speed", "Speed / traffic calming"),
                            ("access", "Accessibility / barrier-free"),
                            ("school_routes", "School routes"),
                            ("mobility_hub", "Mobility hub"),
                            ("public_space", "Public space reclamation"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title_de", models.CharField(max_length=300)),
                ("title_en", models.CharField(blank=True, max_length=300)),
                ("summary_de", models.CharField(blank=True, max_length=500)),
                ("summary_en", models.CharField(blank=True, max_length=500)),
                ("description_de_md", models.TextField(blank=True)),
                ("description_en_md", models.TextField(blank=True)),
                (
                    "geometry",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposed"),
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("rejected", "Rejected"),
                        ],
                        default="proposed",
                        max_length=20,
                    ),
                ),
                (
                    "effort_level",
                    models.CharField(
                        choices=[
                            ("quick_win", "Quick win"),
                            ("medium", "Medium effort"),
                            ("major", "Major project"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_auto_generated", models.BooleanField(default=False)),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw indicators and debug info supporting this measure.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="measures",
                        to="workspaces.district",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measures",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["workspace", "-updated_at"],
                "unique_together": {("workspace", "slug")},
            },
        ),
        migrations.CreateModel(
            name="MeasureScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("climate", "Climate impact"),
                            ("safety", "Traffic safety"),
                            ("quality_of_life", "Quality of life"),
                            ("social", "Social equity / accessibility"),
                            ("feasibility", "Feasibility"),
                            ("cost", "Cost indicator"),
                            ("visibility", "Public visibility"),
                            ("political", "Political viability"),
                            ("goal_alignment", "Alignment with local goals"),
                        ],
                        max_length=30,
                    ),
                ),
                ("raw_value", models.FloatField(help_text="Normalized 0.0–1.0")),
                (
                    "display_value",
                    models.FloatField(help_text="Display-friendly 0–100"),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("rationale_de", models.TextField(blank=True)),
                ("rationale_en", models.TextField(blank=True)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="measures.measure",
                    ),
                ),
            ],
            options={
                "ordering": ["dimension"],
                "unique_together": {("measure", "dimension")},
            },
        ),
    ]
