# Generated by Django 5.0.9 on 2026-08-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_areatarget"),
        ("measures", "0003_add_electrification_category"),
        ("workspaces", "0004_focusarea"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="focus_area",
            field=models.ForeignKey(
                blank=True,
                help_text="Set when this measure belongs to an area plan.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measures",
                to="workspaces.focusarea",
            ),
        ),
        migrations.CreateModel(
            name="AreaPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("assumptions", models.JSONField(blank=True, default=dict)),
                ("baseline", models.JSONField(blank=True, default=dict)),
                ("projection", models.JSONField(blank=True, default=dict)),
                ("space_budget", models.JSONField(blank=True, default=dict)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "area_target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="goals.areatarget",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_plans",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="AreaPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                (
                    "intervention",
                    models.CharField(
                        choices=[
                            ("protected_bike_lane", "Protected cycle lane"),
                            ("safe_crossing", "Safe crossing"),
                            ("speed_limit_30", "30 km/h speed limit"),
                            ("intersection_redesign", "Junction redesign"),
                            ("traffic_calming", "Traffic calming"),
                        ],
                        max_length=40,
                    ),
                ),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("width_required_m", models.FloatField(blank=True, null=True)),
                ("width_available_m", models.FloatField(blank=True, null=True)),
                (
                    "width_confidence",
                    models.CharField(
                        choices=[
                            ("tagged", "Stated in the source data"),
                            ("estimated", "Estimated from lane count"),
                            ("unknown", "Not available"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "space_source",
                    models.CharField(
                        choices=[
                            ("not_needed", "No extra width needed"),
                            ("parking_removal", "Removing kerbside parking"),
                            ("lane_reallocation", "Reallocating a motor-traffic lane"),
                            ("carriageway_narrowing", "Narrowing the carriageway"),
                            ("unknown", "Width unknown — check on site"),
                            ("insufficient", "Does not fit — needs a larger rebuild"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                ("parking_spaces_removed", models.PositiveIntegerField(default=0)),
                ("car_lanes_reallocated", models.PositiveSmallIntegerField(default=0)),
                ("obstacles", models.JSONField(blank=True, default=list)),
                (
                    "affected_baseline",
                    models.FloatField(
                        default=0.0,
                        help_text="Share of the area's baseline harm on this segment.",
                    ),
                ),
                (
                    "affected_severity",
                    models.CharField(
                        choices=[
                            (
                                "fatal_serious",
                                "Includes people killed or seriously injured",
                            ),
                            ("minor_only", "Slight injuries only"),
                        ],
                        default="minor_only",
                        max_length=20,
                    ),
                ),
                ("effect_low", models.FloatField(default=0.0)),
                ("effect_central", models.FloatField(default=0.0)),
                ("effect_high", models.FloatField(default=0.0)),
                ("confidence", models.CharField(default="medium", max_length=10)),
                ("sources", models.JSONField(blank=True, default=list)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_items",
                        to="measures.measure",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="measures.areaplan",
                    ),
                ),
            ],
            options={
                "ordering": ["plan", "rank"],
            },
        ),
    ]
