# Generated by Django 5.0.9 on 2026-04-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkspaceGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Short identifier, e.g. 'modal_shift_2030'",
                        max_length=100,
                    ),
                ),
                ("title_de", models.CharField(max_length=200)),
                ("title_en", models.CharField(blank=True, max_length=200)),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True, help_text="e.g. %, km, t CO2", max_length=50
                    ),
                ),
                (
                    "deadline_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("rationale_de", models.TextField(blank=True)),
                ("rationale_en", models.TextField(blank=True)),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "ordering": ["deadline_year", "title_de"],
                "unique_together": {("workspace", "code")},
            },
        ),
    ]
