# Generated by Django 5.0.9 on 2026-08-18 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0001_initial"),
        ("workspaces", "0004_focusarea"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=100)),
                (
                    "indicator",
                    models.CharField(
                        help_text="Key from the indicator catalogue (goals/indicators.py).",
                        max_length=60,
                    ),
                ),
                (
                    "target_mode",
                    models.CharField(
                        choices=[
                            ("zero", "Zero — no one killed or seriously injured"),
                            ("absolute", "Absolute value"),
                            ("percent", "Percentage change"),
                        ],
                        default="zero",
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("decrease", "Lower is better"),
                            ("increase", "Higher is better"),
                        ],
                        default="decrease",
                        max_length=20,
                    ),
                ),
                ("baseline_value", models.FloatField(blank=True, null=True)),
                (
                    "baseline_meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="How the baseline was computed — years, counts, filters.",
                    ),
                ),
                ("target_value", models.FloatField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=50)),
                (
                    "deadline_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("rationale_de", models.TextField(blank=True)),
                ("rationale_en", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "focus_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="targets",
                        to="workspaces.focusarea",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="area_targets",
                        to="workspaces.workspace",
                    ),
                ),
                (
                    "workspace_goal",
                    models.ForeignKey(
                        blank=True,
                        help_text="City-wide goal this area target contributes to.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="area_targets",
                        to="goals.workspacegoal",
                    ),
                ),
            ],
            options={
                "ordering": ["focus_area", "code"],
                "unique_together": {("focus_area", "code")},
            },
        ),
    ]
